Implementation;Place and Route||OnlineHelp;liberoaction://open_online_help/98369539||Info: I/O Bank and Globals Assigner detected (7) out of (7) I/O Bank(s) with locked I/O technologies.||(null);(null)||(null);(null)
Implementation;Place and Route;RootName:aufgabe1
Implementation;Place and Route||(null)||Please refer to the log file for details about 12 Info(s)||aufgabe1_layout_log.log;liberoaction://open_report/file/aufgabe1_layout_log.log||(null);(null)
Implementation;Generate Bitstream;RootName:aufgabe1
Implementation;Generate Bitstream||(null)||Please refer to the log file for details about 1 Info(s)||aufgabe1_generateBitstream.log;liberoaction://open_report/file/aufgabe1_generateBitstream.log||(null);(null)
HelpInfo,C:\Microchip\Libero_SoC_v2024.1\SynplifyPro\lib\html,fpgahelp.qhc,synerrmsg.mp,C:\Microchip\Libero_SoC_v2024.1\SynplifyPro\bin\assistant
